
platform :ios, '14.0'
use_frameworks!

target "InsuranceApp" do
  pod "PromiseKit", "~> 6.8"
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Generics', :git => 'https://gitlab.com/mahvish10/genericspod'
  pod 'CustomDropDown', :git => 'https://gitlab.com/mahvish10/customdropdownpod'
  pod 'ProfileTableViewController', :git => 'https://gitlab.com/mahvish10/profiletableviewcontrollerpod'
  pod 'PoliciesTableViewController', :git => 'https://gitlab.com/mahvish10/policiestableviewcontrollerpod'
  pod 'DashboardTableViewController', :git => 'https://gitlab.com/mahvish10/dashboardtableviewcontrollerpod'
  pod 'QuoteCollectionViewController', :git => 'https://gitlab.com/mahvish10/quotescollectionviewcontrollerpod'
  pod 'PopupViewController', :git => 'https://gitlab.com/mahvish10/popupviewcontrollerpod'
end

target "InsuranceAppTests" do
  pod "PromiseKit", "~> 6.8"
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Generics', :git => 'https://gitlab.com/mahvish10/genericspod'
  pod 'CustomDropDown', :git => 'https://gitlab.com/mahvish10/customdropdownpod'
  pod 'ProfileTableViewController', :git => 'https://gitlab.com/mahvish10/profiletableviewcontrollerpod'
  pod 'PoliciesTableViewController', :git => 'https://gitlab.com/mahvish10/policiestableviewcontrollerpod'
  pod 'DashboardTableViewController', :git => 'https://gitlab.com/mahvish10/dashboardtableviewcontrollerpod'
  pod 'QuoteCollectionViewController', :git => 'https://gitlab.com/mahvish10/quotescollectionviewcontrollerpod'
  pod 'PopupViewController', :git => 'https://gitlab.com/mahvish10/popupviewcontrollerpod'
end
